name: Uptime Kuma
description: A fancy self-hosted monitoring tool
version: 1.11.4
slug: uptime-kuma
arch:
  - amd64
  - aarch64
  - armv7
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web UI
map:
  - config:rw
image: louislam/uptime-kuma
webui: http://[HOST]:[PORT:3001]
environment:
  DATA_DIR: /config/uptime-kuma/
